name: dartboot_util
description: The util library for DartBoot framework.
version: 1.0.1
homepage: https://github.com/dartboot/dartboot_util

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  uuid: ^2.2.2

